// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkfwuyrusdelwfzospgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZnd1eXJ1c2RlbHdmem9zcGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTkzNTMsImV4cCI6MjA2NTEzNTM1M30.7rLh0X7M9Sxu-ot-0htVQjVi-QNo9uNm4tOJ58aZwH0";
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);